language: node_js
sudo: required

before_script:
  - sudo apt-get install g++ build-essential
  - npm install -g @angular/cli

stages:
  - test
  - build


jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: npm run test-headless
    - stage: test
      name: "Linting"
      script: ng lint
    - stage: build
      name: "Build frontend"
      script: "ng build --prod --release"
      if: branch = master
      